/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "CycleStruct.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(AD_ChannelEntry, AD_ChannelEntry, AUTO)


PB_BIND(AD_SerialPacket, AD_SerialPacket, AUTO)



