/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_SRC_CYCLESTRUCT_PB_H_INCLUDED
#define PB_SRC_CYCLESTRUCT_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _AD_ChannelEntry {
    float avgPps;
    uint32_t dwellMs;
    float zScore;
} AD_ChannelEntry;

typedef struct _AD_SerialPacket {
    uint32_t magic;
    uint32_t type;
    uint32_t cycleNum;
    uint32_t cycleTotal;
    uint32_t allTimeTotal;
    float globalMean;
    float globalStdDev;
    pb_size_t channels_count;
    AD_ChannelEntry channels[13];
} AD_SerialPacket;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define AD_ChannelEntry_init_default             {0, 0, 0}
#define AD_SerialPacket_init_default             {0, 0, 0, 0, 0, 0, 0, 0, {AD_ChannelEntry_init_default, AD_ChannelEntry_init_default, AD_ChannelEntry_init_default, AD_ChannelEntry_init_default, AD_ChannelEntry_init_default, AD_ChannelEntry_init_default, AD_ChannelEntry_init_default, AD_ChannelEntry_init_default, AD_ChannelEntry_init_default, AD_ChannelEntry_init_default, AD_ChannelEntry_init_default, AD_ChannelEntry_init_default, AD_ChannelEntry_init_default}}
#define AD_ChannelEntry_init_zero                {0, 0, 0}
#define AD_SerialPacket_init_zero                {0, 0, 0, 0, 0, 0, 0, 0, {AD_ChannelEntry_init_zero, AD_ChannelEntry_init_zero, AD_ChannelEntry_init_zero, AD_ChannelEntry_init_zero, AD_ChannelEntry_init_zero, AD_ChannelEntry_init_zero, AD_ChannelEntry_init_zero, AD_ChannelEntry_init_zero, AD_ChannelEntry_init_zero, AD_ChannelEntry_init_zero, AD_ChannelEntry_init_zero, AD_ChannelEntry_init_zero, AD_ChannelEntry_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define AD_ChannelEntry_avgPps_tag               1
#define AD_ChannelEntry_dwellMs_tag              2
#define AD_ChannelEntry_zScore_tag               3
#define AD_SerialPacket_magic_tag                1
#define AD_SerialPacket_type_tag                 2
#define AD_SerialPacket_cycleNum_tag             3
#define AD_SerialPacket_cycleTotal_tag           4
#define AD_SerialPacket_allTimeTotal_tag         5
#define AD_SerialPacket_globalMean_tag           6
#define AD_SerialPacket_globalStdDev_tag         7
#define AD_SerialPacket_channels_tag             8

/* Struct field encoding specification for nanopb */
#define AD_ChannelEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    avgPps,            1) \
X(a, STATIC,   SINGULAR, UINT32,   dwellMs,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    zScore,            3)
#define AD_ChannelEntry_CALLBACK NULL
#define AD_ChannelEntry_DEFAULT NULL

#define AD_SerialPacket_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   magic,             1) \
X(a, STATIC,   SINGULAR, UINT32,   type,              2) \
X(a, STATIC,   SINGULAR, UINT32,   cycleNum,          3) \
X(a, STATIC,   SINGULAR, UINT32,   cycleTotal,        4) \
X(a, STATIC,   SINGULAR, UINT32,   allTimeTotal,      5) \
X(a, STATIC,   SINGULAR, FLOAT,    globalMean,        6) \
X(a, STATIC,   SINGULAR, FLOAT,    globalStdDev,      7) \
X(a, STATIC,   REPEATED, MESSAGE,  channels,          8)
#define AD_SerialPacket_CALLBACK NULL
#define AD_SerialPacket_DEFAULT NULL
#define AD_SerialPacket_channels_MSGTYPE AD_ChannelEntry

extern const pb_msgdesc_t AD_ChannelEntry_msg;
extern const pb_msgdesc_t AD_SerialPacket_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define AD_ChannelEntry_fields &AD_ChannelEntry_msg
#define AD_SerialPacket_fields &AD_SerialPacket_msg

/* Maximum encoded size of messages (where known) */
#define AD_ChannelEntry_size                     16
#define AD_SerialPacket_size                     274
#define SRC_CYCLESTRUCT_PB_H_MAX_SIZE            AD_SerialPacket_size

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
